name: Bandit scan, Semgrep scan, Gitleaks scan, OWASP ZAP scan (DAST)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  git_leaks_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: git leaks scan
        run: docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --no-git --source="/path" -v --config="/path/.gitleaks.toml"
  bandit_scan:
    runs-on: ubuntu-latest  
    steps:
      - name: Bandit scan
        run: |
          pip3 install bandit
          bandit -r ./ -f html -o bandit_report.html
      - name: 
      - name: build go app
        run: docker build -t myapplication .
      - name: Run go app as container
        run: docker run -d -e host=0.0.0.0 --name flask_api myapplication
      - name: Create directory
        run: |
          mkdir $(pwd)/zap/
          chmod 777 $(pwd)/zap/
      - name: Run container to generate report
        run: docker run -v $(pwd)/zap/:/zap/wrk/ --link flask_api -t zaproxy/zap-stable zap-api-scan.py -t http://flask_api:3300 -r report.html -J report.yaml -f openapi || true
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: zap/report.html
